version: '3.9'
services:
  zookeeper: 
    restart: always
    container_name: zk #容器的名称
    image: zookeeper  #镜像地址
    ports:
      - 2182:2181 #指定端口


  dubbo-admin:
    restart: always
    image: apache/dubbo-admin
    container_name: dubbo-admin
    ports:
      - 9600:8080
    environment:
      admin.registry.address: zookeeper://192.168.11.139:2182
      admin.config-center: zookeeper://192.168.11.139:2182
      admin.metadata-report.address: zookeeper://192.168.11.139:2182
